# Travis-CI Build for gf2
# see travis-ci.org for details

language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug

script: 
  - mkdir build && cd build 
  - cmake -DBUILD_TYPE=$BUILD_TYPE ..
  - make
  - ctest -V
